version: '2'

services:

  borzoo.web:
    container_name: borzoo.web
    build:
      context: ../src/Borzoo.Web/bin/publish
      dockerfile: Borzoo.Web.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - SQLite_Migrations_Script=/tmp/migrations.sql
      - SQLite_Db_Path=/app/data/borzoo.sql
    volumes:
      - /var/borzoo-data/:/app/data/
    networks:
      - borzoo

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - /var/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - borzoo.web
    networks:
      - borzoo

networks: 
  borzoo:
    driver: bridge
